apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
namespace: ekl-k8s-dev
commonLabels:
  app: ekl-backend-ws-dev
patches:
  - path: configmap-dev.yaml
  - path: deployment-dev.yaml
images:
  - name: ekl-backend-ws
    newName: ponyworld/ekl-backend-ws
    newTag: {{IMAGE_TAG}}