apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
namespace: ekl-dev
commonLabels:
  app: ekl-backend-ws-dev
patches:
  - path: configmap-dev.yaml
  - path: deployment-dev.yaml
  - path: virtualservice-dev.yaml
  - path: service-dev.yaml
images:
  - name: ekl-backend-ws
    newName: ponyworld/ekl-backend-ws-dev
    newTag: 20240702T233752