apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ekl-backend-ws
spec:
  hosts:
    - ekl-backend-ws-dev.ponyworld.io
  tls:
    - match:
      - port: 443
        sniHosts:
          - ekl-backend-ws-dev.ponyworld.io
      route:
        - destination:
            host: ekl-backend-ws-dev.ekl-dev.svc.cluster.local
            port:
              number: 8443
