apiVersion: v1
kind: Service
metadata:
  name: ekl-backend-ws
spec:
  selector:
    app: ekl-backend-ws
  ports:
    - port: 8443
      name: https
      targetPort: 8443
      protocol: TCP
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP