apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ekl-backend-ws
spec:
  hosts:
    - ekl-backend-ws.ponyworld.io
  gateways:
    - ekl-backend-ws
  tls:
    - match:
      - port: 443
      route:
      - destination:
          host: ekl-backend-ws